"""create enrollment and lesson tables

Revision ID: 3ad81acee8e3
Revises: 95b8dcb0c0e7
Create Date: 2023-09-23 17:07:40.031447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ad81acee8e3'
down_revision: Union[str, None] = '95b8dcb0c0e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrollments',
    sa.Column('enrollment_id', sa.Integer(), nullable=False),
    sa.Column('enrollment_message', sa.String(), nullable=False),
    sa.Column('student_fkey', sa.Integer(), nullable=False),
    sa.Column('course_fkey', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_fkey'], ['courses.course_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_fkey'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('enrollment_id')
    )
    op.create_index(op.f('ix_enrollments_enrollment_id'), 'enrollments', ['enrollment_id'], unique=False)
    op.create_table('lessons',
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('lesson_title', sa.String(), nullable=False),
    sa.Column('lesson_content', sa.String(), nullable=False),
    sa.Column('user_fkey', sa.Integer(), nullable=False),
    sa.Column('course_fkey', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_fkey'], ['courses.course_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_fkey'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lesson_id')
    )
    op.create_index(op.f('ix_lessons_lesson_id'), 'lessons', ['lesson_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lessons_lesson_id'), table_name='lessons')
    op.drop_table('lessons')
    op.drop_index(op.f('ix_enrollments_enrollment_id'), table_name='enrollments')
    op.drop_table('enrollments')
    # ### end Alembic commands ###
